### ISSUE TITLE
Enhancement Proposal: Weight in # of unbalanced epochs

### ISSUE THREAD

**Issue by calypso-it** [marinade-finance/staking-status#1]
Currently, validators are staked in the order of `MOST-UNBALANCED to least unbalanced` without any account for the amount of epochs, a validator has been stuck unbalanced.

With the constant stream of new solana validators onboarded every week (~25), some previously staked validators will stay unbalanced.

To balance seniority (validator missing stake `X` for `Y` epochs) against the total missing stake `X`, we propose weighting in `Y` in the calculations of the staking order.

Example: Order defined by `X*Y` instead of `X` so that a validator missing 10k stake for 4 epochs has a higher priority to be balanced than a new validator just waiting for 1 epoch.

**Comment by calypso-it** [comment]
cc @luciotato

**Comment by michaelh-laine** [comment]
In addition, or alternatively, I suggest implementing a cap to how much Marinade will stake a validator. This could be 100% or 200% of their current active stake, and this would be considered for every epoch, so new validators that qualify for 60k stake might go like this:

Current: 100 SOL -> 60,000 SOL 
Proposed: 100 SOL -> 300 SOL -> 900 SOL -> 2,700 SOL -> 8,100 SOL -> 24,300 SOL -> 60,000 SOL

This has multiple benefits:
- Many startup validators might keep commission low to capture stake pools then increase it, this way they can't do so as rapidly
- Reliability and whether a validator will stay operative is much less certain with brand new nodes, they might shut down due to losses and Marinade is stuck staking a delinquent node until they can force destake
- Preserves reserve for broader redistribution per epoch
- Encourages healthier validator behaviour where they seek out stake elsewhere and don't count on a single massive pool stake hitting them within a few epochs of starting, reduces their dependence on Marinade and Marinade's disproportionate control/impact on small nodes where 90%+ of their stake comes from Marinade
